export const englishInternalWeapons = new Map([
  ["Sploosh-o-matic", "Shooter_Short_00"],
  ["Neo Sploosh-o-matic", "Shooter_Short_01"],
  ["Sploosh-o-matic 7", "Shooter_Short_02"],
  ["Splattershot Jr.", "Shooter_First_00"],
  ["Custom Splattershot Jr.", "Shooter_First_01"],
  ["Kensa Splattershot Jr.", "Shooter_First_02"],
  ["Splash-o-matic", "Shooter_Precision_00"],
  ["Neo Splash-o-matic", "Shooter_Precision_01"],
  ["Aerospray MG", "Shooter_Blaze_00"],
  ["Aerospray RG", "Shooter_Blaze_01"],
  ["Aerospray PG", "Shooter_Blaze_02"],
  ["Splattershot", "Shooter_Normal_00"],
  ["Hero Shot Replica", "Shooter_Normal_H"],
  ["Tentatek Splattershot", "Shooter_Normal_01"],
  ["Octo Shot Replica", "Shooter_Normal_Oct"],
  ["Kensa Splattershot", "Shooter_Normal_02"],
  [".52 Gal", "Shooter_Gravity_00"],
  [".52 Gal Deco", "Shooter_Gravity_01"],
  ["Kensa .52 Gal", "Shooter_Gravity_02"],
  ["N-ZAP '85", "Shooter_QuickMiddle_00"],
  ["N-ZAP '89", "Shooter_QuickMiddle_01"],
  ["N-ZAP '83", "Shooter_QuickMiddle_02"],
  ["Splattershot Pro", "Shooter_Expert_00"],
  ["Forge Splattershot Pro", "Shooter_Expert_01"],
  ["Kensa Splattershot Pro", "Shooter_Expert_02"],
  [".96 Gal", "Shooter_Heavy_00"],
  [".96 Gal Deco", "Shooter_Heavy_01"],
  ["Jet Squelcher", "Shooter_Long_00"],
  ["Custom Jet Squelcher", "Shooter_Long_01"],
  ["L-3 Nozzlenose", "Shooter_TripleQuick_00"],
  ["L-3 Nozzlenose D", "Shooter_TripleQuick_01"],
  ["Kensa L-3 Nozzlenose", "Shooter_TripleQuick_02"],
  ["H-3 Nozzlenose", "Shooter_TripleMiddle_00"],
  ["H-3 Nozzlenose D", "Shooter_TripleMiddle_01"],
  ["Cherry H-3 Nozzlenose", "Shooter_TripleMiddle_02"],
  ["Squeezer", "Shooter_Flash_00"],
  ["Foil Squeezer", "Shooter_Flash_01"],
  ["Luna Blaster", "Shooter_BlasterShort_00"],
  ["Luna Blaster Neo", "Shooter_BlasterShort_01"],
  ["Kensa Luna Blaster", "Shooter_BlasterShort_02"],
  ["Blaster", "Shooter_BlasterMiddle_00"],
  ["Hero Blaster Replica", "Shooter_BlasterMiddle_H"],
  ["Custom Blaster", "Shooter_BlasterMiddle_01"],
  ["Range Blaster", "Shooter_BlasterLong_00"],
  ["Custom Range Blaster", "Shooter_BlasterLong_01"],
  ["Grim Range Blaster", "Shooter_BlasterLong_02"],
  ["Rapid Blaster", "Shooter_BlasterLight_00"],
  ["Rapid Blaster Deco", "Shooter_BlasterLight_01"],
  ["Kensa Rapid Blaster", "Shooter_BlasterLight_02"],
  ["Rapid Blaster Pro", "Shooter_BlasterLightLong_00"],
  ["Rapid Blaster Pro Deco", "Shooter_BlasterLightLong_01"],
  ["Clash Blaster", "Shooter_BlasterLightShort_00"],
  ["Clash Blaster Neo", "Shooter_BlasterLightShort_01"],
  ["Carbon Roller", "Roller_Compact_00"],
  ["Carbon Roller Deco", "Roller_Compact_01"],
  ["Splat Roller", "Roller_Normal_00"],
  ["Hero Roller Replica", "Roller_Normal_H"],
  ["Krak-On Splat Roller", "Roller_Normal_01"],
  ["Kensa Splat Roller", "Roller_Normal_02"],
  ["Dynamo Roller", "Roller_Heavy_00"],
  ["Gold Dynamo Roller", "Roller_Heavy_01"],
  ["Kensa Dynamo Roller", "Roller_Heavy_02"],
  ["Flingza Roller", "Roller_Hunter_00"],
  ["Foil Flingza Roller", "Roller_Hunter_01"],
  ["Inkbrush", "Roller_BrushMini_00"],
  ["Inkbrush Nouveau", "Roller_BrushMini_01"],
  ["Permanent Inkbrush", "Roller_BrushMini_02"],
  ["Octobrush", "Roller_BrushNormal_00"],
  ["Herobrush Replica", "Roller_BrushNormal_H"],
  ["Octobrush Nouveau", "Roller_BrushNormal_01"],
  ["Kensa Octobrush", "Roller_BrushNormal_02"],
  ["Classic Squiffer", "Charger_Quick_00"],
  ["New Squiffer", "Charger_Quick_01"],
  ["Fresh Squiffer", "Charger_Quick_02"],
  ["Splat Charger", "Charger_Normal_00"],
  ["Hero Charger Replica", "Charger_Normal_H"],
  ["Firefin Splat Charger", "Charger_Normal_01"],
  ["Kensa Charger", "Charger_Normal_02"],
  ["Splatterscope", "Charger_NormalScope_00"],
  ["Firefin Splatterscope", "Charger_NormalScope_01"],
  ["Kensa Splatterscope", "Charger_NormalScope_02"],
  ["E-liter 4K", "Charger_Long_00"],
  ["Custom E-liter 4K", "Charger_Long_01"],
  ["E-liter 4K Scope", "Charger_LongScope_00"],
  ["Custom E-liter 4K Scope", "Charger_LongScope_01"],
  ["Bamboozler 14 Mk I", "Charger_Light_00"],
  ["Bamboozler 14 Mk II", "Charger_Light_01"],
  ["Bamboozler 14 Mk III", "Charger_Light_02"],
  ["Goo Tuber", "Charger_Keeper_00"],
  ["Custom Goo Tuber", "Charger_Keeper_01"],
  ["Slosher", "Slosher_Strong_00"],
  ["Hero Slosher Replica", "Slosher_Strong_H"],
  ["Slosher Deco", "Slosher_Strong_01"],
  ["Soda Slosher", "Slosher_Strong_02"],
  ["Tri-Slosher", "Slosher_Diffusion_00"],
  ["Tri-Slosher Nouveau", "Slosher_Diffusion_01"],
  ["Sloshing Machine", "Slosher_Launcher_00"],
  ["Sloshing Machine Neo", "Slosher_Launcher_01"],
  ["Kensa Sloshing Machine", "Slosher_Launcher_02"],
  ["Bloblobber", "Slosher_Bathtub_00"],
  ["Bloblobber Deco", "Slosher_Bathtub_01"],
  ["Explosher", "Slosher_Washtub_00"],
  ["Custom Explosher", "Slosher_Washtub_01"],
  ["Mini Splatling", "Spinner_Quick_00"],
  ["Zink Mini Splatling", "Spinner_Quick_01"],
  ["Kensa Mini Splatling", "Spinner_Quick_02"],
  ["Heavy Splatling", "Spinner_Standard_00"],
  ["Hero Splatling Replica", "Spinner_Standard_H"],
  ["Heavy Splatling Deco", "Spinner_Standard_01"],
  ["Heavy Splatling Remix", "Spinner_Standard_02"],
  ["Hydra Splatling", "Spinner_Hyper_00"],
  ["Custom Hydra Splatling", "Spinner_Hyper_01"],
  ["Ballpoint Splatling", "Spinner_Downpour_00"],
  ["Ballpoint Splatling Nouveau", "Spinner_Downpour_01"],
  ["Nautilus 47", "Spinner_Serein_00"],
  ["Nautilus 79", "Spinner_Serein_01"],
  ["Dapple Dualies", "Twins_Short_00"],
  ["Dapple Dualies Nouveau", "Twins_Short_01"],
  ["Clear Dapple Dualies", "Twins_Short_02"],
  ["Splat Dualies", "Twins_Normal_00"],
  ["Hero Dualie Replicas", "Twins_Normal_H"],
  ["Enperry Splat Dualies", "Twins_Normal_01"],
  ["Kensa Splat Dualies", "Twins_Normal_02"],
  ["Glooga Dualies", "Twins_Gallon_00"],
  ["Glooga Dualies Deco", "Twins_Gallon_01"],
  ["Kensa Glooga Dualies", "Twins_Gallon_02"],
  ["Dualie Squelchers", "Twins_Dual_00"],
  ["Custom Dualie Squelchers", "Twins_Dual_01"],
  ["Dark Tetra Dualies", "Twins_Stepper_00"],
  ["Light Tetra Dualies", "Twins_Stepper_01"],
  ["Splat Brella", "Umbrella_Normal_00"],
  ["Hero Brella Replica", "Umbrella_Normal_H"],
  ["Sorella Brella", "Umbrella_Normal_01"],
  ["Tenta Brella", "Umbrella_Wide_00"],
  ["Tenta Sorella Brella", "Umbrella_Wide_01"],
  ["Tenta Camo Brella", "Umbrella_Wide_02"],
  ["Undercover Brella", "Umbrella_Compact_00"],
  ["Undercover Sorella Brella", "Umbrella_Compact_01"],
  ["Kensa Undercover Brella", "Umbrella_Compact_02"],
]);
